#!/usr/bin/env node
/* eslint-disable no-undef -- Node ESM build tool */
/**
 * export-aw-data.mjs — snapshot REAL active-work state into a typed fixture the
 * Lab specimens import. Runs the `active-work` CLI for structured data and reads
 * a focus initiative's prose (brief body, handoff, recent session bodies) so the
 * session/initiative readers render real content. Re-run to refresh.
 *
 * Output: ../data/aw-data.ts
 */
import { promises as fs } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
import os from 'node:os';

const pexec = promisify(execFile);
const ACTIVE_ROOT =
  process.env.ACTIVE_ROOT ||
  path.join(os.homedir(), 'Library', 'Application Support', 'active-work');
const FOCUS = process.argv[2] || 'active-work';
const OUT = path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'data', 'aw-data.ts');

async function aw(args) {
  const { stdout } = await pexec('active-work', ['--json', ...args], {
    maxBuffer: 64 * 1024 * 1024,
  });
  const env = JSON.parse(stdout);
  if (!env.ok) throw new Error(`aw ${args.join(' ')}: ${env.error}`);
  return env.data;
}

/** Split a markdown file into {frontmatter-string, body}. */
async function readMd(p) {
  let raw;
  try {
    raw = await fs.readFile(p, 'utf8');
  } catch {
    return { body: '' };
  }
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  return m ? { fm: m[1], body: m[2].trim() } : { body: raw.trim() };
}

function clip(text, maxLines = 80) {
  const lines = text.split('\n');
  return lines.length > maxLines ? lines.slice(0, maxLines).join('\n') + '\n\n…' : text;
}

async function main() {
  const list = await aw(['list']);
  const taskData = await aw(['task', 'list', FOCUS, '--all-initiatives', '--status', 'all']);
  const tasks = taskData.tasks ?? [];

  // Focus initiative detail: brief body, handoff, recent session bodies.
  const dir = path.join(ACTIVE_ROOT, FOCUS);
  const brief = await readMd(path.join(dir, 'brief.md'));
  const handoff = await readMd(path.join(dir, 'handoff.md'));

  let sessionList = { sessions: [] };
  try {
    sessionList = await aw(['session', 'list', FOCUS, '--limit', '12']);
  } catch {
    /* some initiatives have no sessions */
  }
  const sessionsDir = path.join(dir, 'sessions');
  const sessions = [];
  for (const s of (sessionList.sessions ?? []).slice(0, 8)) {
    const md = await readMd(path.join(sessionsDir, s.filename));
    sessions.push({
      filename: s.filename,
      session_id: s.frontmatter.session_id,
      started: s.frontmatter.started,
      ended: s.frontmatter.ended,
      track: s.frontmatter.track,
      first_line: s.first_line,
      body: clip(md.body, 90),
    });
  }

  // Brief frontmatter for the focus initiative (find it in the list).
  const flat = list.sections.flatMap((sec) => sec.items);
  const focusBrief = flat.find((i) => i.slug === FOCUS) ?? null;

  const data = {
    generatedNote: 'Real active-work state, snapshotted via the CLI. Regenerate with tools/export-aw-data.mjs.',
    sections: list.sections,
    parseErrors: list.parse_errors ?? [],
    tasks,
    focus: {
      slug: FOCUS,
      brief: focusBrief,
      briefBody: clip(brief.body, 40),
      handoffBody: clip(handoff.body, 80),
      sessions,
    },
  };

  const module = `// AUTO-GENERATED by tools/export-aw-data.mjs — a real snapshot of active-work
// state (initiatives, tasks, sessions). Do not edit by hand; re-run to refresh.
/* eslint-disable */

export type InitiativeState = 'focused' | 'backburner' | 'paused' | 'done';
export type TaskSeverity = 'critical' | 'high' | 'medium' | 'low';
export type TaskStatus = 'open' | 'done';

export interface InitiativeSummary {
  slug: string;
  title: string;
  state: InitiativeState;
  rank?: number;
  ship_target?: string;
  paused_since?: string;
  updated: string;
}
export interface InitiativeSection { heading: string; items: InitiativeSummary[] }

export interface AwTask {
  id: string;
  slug: string;
  title: string;
  priority: number;
  severity?: TaskSeverity;
  estimate?: number;
  status: TaskStatus;
  done_when?: string;
  tags?: string[];
  notes?: string;
  created: string;
  updated: string;
  done_at?: string | null;
}

export interface AwSession {
  filename: string;
  session_id: string;
  started: string;
  ended: string;
  track: string;
  first_line: string;
  body: string;
}

export interface AwData {
  generatedNote: string;
  sections: InitiativeSection[];
  parseErrors: { slug: string; error: string }[];
  tasks: AwTask[];
  focus: {
    slug: string;
    brief: InitiativeSummary | null;
    briefBody: string;
    handoffBody: string;
    sessions: AwSession[];
  };
}

export const awData: AwData = ${JSON.stringify(data, null, 2)};
`;

  await fs.writeFile(OUT, module, 'utf8');
  console.log(
    `wrote ${OUT}\n  initiatives: ${flat.length}  tasks: ${tasks.length}  ` +
      `focus=${FOCUS} sessions: ${sessions.length}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
