import type { Meta, StoryObj } from '@storybook/react-vite'
import { useMemo, useState } from 'react'
import { getSemanticColors } from '../theme/tokens/semantic'
import graph from './arch-graph.json'

/**
 * `Docs/Architecture` — a deterministic, regenerable map of the component library.
 * Generated by `scripts/arch-graph.mjs` (codewatch symbol graph + a light import-parse
 * of the consuming apps) → `arch-graph.json`. Two first-class sections: the internal
 * dependency diagram (tiered by composition depth) and the health audit (dead code,
 * primitive-substitution leaks, extraction candidates). Regenerate with
 * `node scripts/arch-graph.mjs --reindex`.
 */

const C = getSemanticColors('dark')

type Comp = (typeof graph.components)[number]
type Tier = 'atom' | 'molecule' | 'organism' | 'page'
const TIERS: Tier[] = ['atom', 'molecule', 'organism', 'page']
const TIER_LABEL: Record<Tier, string> = {
  atom: 'Atoms',
  molecule: 'Molecules',
  organism: 'Organisms',
  page: 'Pages',
}

const VERDICT: Record<string, { label: string; color: string }> = {
  'keep-core': { label: 'Core (lib + app)', color: C['status-success'] },
  'keep-internal': { label: 'Internal only', color: C['status-info'] },
  'keep-app': { label: 'App-facing leaf', color: C['brand-secondary'] },
  'keep-page': { label: 'Shipped page', color: C['status-success'] },
  'demo-only': { label: 'Demo page (unshipped)', color: C['status-warning'] },
  remove: { label: 'Throwaway → remove', color: C['text-tertiary'] },
  dead: { label: 'Dead everywhere', color: C['status-error-vivid'] },
}
const verdictColor = (v: string) => VERDICT[v]?.color ?? C['text-tertiary']

// ---- layout ---------------------------------------------------------------
const COL_W = 250
const NODE_H = 24
const NODE_GAP = 6
const ROW = NODE_H + NODE_GAP
const PAD_TOP = 40
const NODE_W = 176

function useLayout() {
  return useMemo(() => {
    const cols: Record<Tier, Comp[]> = { atom: [], molecule: [], organism: [], page: [] }
    for (const c of graph.components) cols[c.tier as Tier].push(c)
    for (const t of TIERS) cols[t].sort((a, b) => b.leak.score - a.leak.score)
    const pos: Record<string, { x: number; y: number }> = {}
    TIERS.forEach((t, ci) => {
      cols[t].forEach((c, ri) => {
        pos[c.name] = { x: ci * COL_W + 20, y: PAD_TOP + ri * ROW }
      })
    })
    const height = PAD_TOP + Math.max(...TIERS.map((t) => cols[t].length)) * ROW + 20
    return { cols, pos, height, width: TIERS.length * COL_W + 20 }
  }, [])
}

// ---- dependency diagram ---------------------------------------------------
function Diagram() {
  const { cols, pos, height, width } = useLayout()
  const [hover, setHover] = useState<string | null>(null)

  const neighbors = useMemo(() => {
    if (!hover) return null
    const set = new Set<string>([hover])
    for (const [a, b] of graph.edges) {
      if (a === hover) set.add(b)
      if (b === hover) set.add(a)
    }
    return set
  }, [hover])

  const edgePath = (a: string, b: string) => {
    const s = pos[a]
    const t = pos[b]
    if (!s || !t) return null
    // composer (a, higher tier/right) → composed (b, lower tier/left): exit left, enter right
    const x1 = s.x
    const y1 = s.y + NODE_H / 2
    const x2 = t.x + NODE_W
    const y2 = t.y + NODE_H / 2
    const mx = (x1 + x2) / 2
    return `M${x1},${y1} C${mx},${y1} ${mx},${y2} ${x2},${y2}`
  }

  return (
    <div
      style={{
        overflow: 'auto',
        border: `1px solid ${C['border-subtle']}`,
        borderRadius: 8,
        background: C['surface-base'],
      }}
    >
      <svg width={width} height={height} style={{ display: 'block', minWidth: '100%' }}>
        {TIERS.map((t, ci) => (
          <text
            key={t}
            x={ci * COL_W + 20}
            y={22}
            fill={C['text-secondary']}
            fontSize={12}
            fontWeight={700}
            fontFamily="Inter, sans-serif"
          >
            {TIER_LABEL[t]} · {cols[t].length}
          </text>
        ))}
        {graph.edges.map(([a, b], i) => {
          const d = edgePath(a, b)
          if (!d) return null
          const active = neighbors ? neighbors.has(a) && neighbors.has(b) : false
          const dim = neighbors && !active
          return (
            <path
              key={i}
              d={d}
              fill="none"
              stroke={active ? C['brand-primary'] : C['border-prominent']}
              strokeWidth={active ? 1.8 : 1}
              opacity={dim ? 0.04 : active ? 0.95 : 0.45}
            />
          )
        })}
        {graph.components.map((c) => {
          const p = pos[c.name]
          const dim = neighbors ? !neighbors.has(c.name) : false
          return (
            <g
              key={c.name}
              transform={`translate(${p.x},${p.y})`}
              opacity={dim ? 0.28 : 1}
              style={{ cursor: 'pointer' }}
              onMouseEnter={() => setHover(c.name)}
              onMouseLeave={() => setHover(null)}
            >
              <rect
                width={NODE_W}
                height={NODE_H}
                rx={5}
                fill={C['surface-raised']}
                stroke={verdictColor(c.verdict)}
                strokeWidth={c.verdict === 'dead' ? 1.6 : 1}
              />
              <rect width={4} height={NODE_H} rx={2} fill={verdictColor(c.verdict)} />
              <text
                x={11}
                y={NODE_H / 2 + 4}
                fill={C['text-primary']}
                fontSize={11.5}
                fontFamily="Inter, sans-serif"
              >
                {c.name}
              </text>
              <text
                x={NODE_W - 9}
                y={NODE_H / 2 + 4}
                textAnchor="end"
                fill={C['text-tertiary']}
                fontSize={9.5}
                fontFamily="monospace"
              >
                {c.libDependents}·{c.xproj.total}
              </text>
            </g>
          )
        })}
      </svg>
    </div>
  )
}

// ---- health tables --------------------------------------------------------
function Chip({ color, children }: { color: string; children: React.ReactNode }) {
  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        padding: '3px 9px',
        borderRadius: 999,
        background: C['surface-raised'],
        border: `1px solid ${C['border-subtle']}`,
        fontSize: 12,
        color: C['text-secondary'],
      }}
    >
      <span style={{ width: 8, height: 8, borderRadius: 999, background: color }} />
      {children}
    </span>
  )
}

function Th({ children, right }: { children: React.ReactNode; right?: boolean }) {
  return (
    <th
      style={{
        textAlign: right ? 'right' : 'left',
        padding: '6px 12px',
        color: C['text-tertiary'],
        fontSize: 11,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        borderBottom: `1px solid ${C['border-subtle']}`,
      }}
    >
      {children}
    </th>
  )
}
function Td({
  children,
  right,
  mono,
}: {
  children: React.ReactNode
  right?: boolean
  mono?: boolean
}) {
  return (
    <td
      style={{
        textAlign: right ? 'right' : 'left',
        padding: '6px 12px',
        color: C['text-primary'],
        fontSize: 13,
        fontFamily: mono ? 'monospace' : 'inherit',
        borderBottom: `1px solid ${C['border-subtle']}`,
      }}
    >
      {children}
    </td>
  )
}

function DeadTable() {
  const dead = graph.components.filter(
    (c) => c.verdict === 'dead' || c.verdict === 'remove' || c.verdict === 'demo-only'
  )
  return (
    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
      <thead>
        <tr>
          <Th>Component</Th>
          <Th>Tier</Th>
          <Th>Verdict</Th>
          <Th right>lib</Th>
          <Th right>story</Th>
          <Th right>app</Th>
        </tr>
      </thead>
      <tbody>
        {dead.map((c) => (
          <tr key={c.name}>
            <Td>{c.name}</Td>
            <Td>{c.tier}</Td>
            <Td>
              <Chip color={verdictColor(c.verdict)}>{VERDICT[c.verdict]?.label ?? c.verdict}</Chip>
            </Td>
            <Td right mono>
              {c.libDependents}
            </Td>
            <Td right mono>
              {c.storyRefs}
            </Td>
            <Td right mono>
              {c.xproj.total}
            </Td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

function SubstitutionTable() {
  const sub = graph.summary.substitution
  const prims = Object.keys(sub['library(titan)'] ?? {})
  const scopes = Object.keys(sub)
  return (
    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
      <thead>
        <tr>
          <Th>Scope</Th>
          {prims.map((p) => (
            <Th key={p} right>
              {p}
            </Th>
          ))}
        </tr>
      </thead>
      <tbody>
        {scopes.map((s) => (
          <tr key={s}>
            <Td>{s}</Td>
            {prims.map((p) => {
              const v = (sub as Record<string, Record<string, number>>)[s][p] ?? 0
              return (
                <Td key={p} right mono>
                  {v > 0 ? v : '·'}
                </Td>
              )
            })}
          </tr>
        ))}
      </tbody>
    </table>
  )
}

function ExtractionTable() {
  return (
    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
      <thead>
        <tr>
          <Th>Component</Th>
          <Th>Tier</Th>
          <Th right>{'<View>'}</Th>
          <Th right>{'<Text>'}</Th>
          <Th right>{'style={{'}</Th>
          <Th right>rawHex</Th>
          <Th right>loc</Th>
          <Th right>score</Th>
        </tr>
      </thead>
      <tbody>
        {graph.summary.extractionTop.map((r) => (
          <tr key={r.name}>
            <Td>{r.name}</Td>
            <Td>{r.tier}</Td>
            <Td right mono>
              {r.rawView}
            </Td>
            <Td right mono>
              {r.rawText}
            </Td>
            <Td right mono>
              {r.inlineStyle}
            </Td>
            <Td right mono>
              {r.rawHex > 0 ? r.rawHex : '·'}
            </Td>
            <Td right mono>
              {r.loc}
            </Td>
            <Td right mono>
              {r.score}
            </Td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

function Section({
  title,
  subtitle,
  children,
}: {
  title: string
  subtitle: string
  children: React.ReactNode
}) {
  return (
    <section style={{ marginTop: 28 }}>
      <h2
        style={{
          color: C['text-primary'],
          fontSize: 18,
          fontWeight: 700,
          margin: 0,
          fontFamily: 'Inter, sans-serif',
        }}
      >
        {title}
      </h2>
      <p
        style={{
          color: C['text-tertiary'],
          fontSize: 13,
          margin: '4px 0 12px',
          fontFamily: 'Inter, sans-serif',
        }}
      >
        {subtitle}
      </p>
      {children}
    </section>
  )
}

function ArchitecturePage() {
  const dead = graph.components.filter((c) => c.verdict === 'dead').length
  const libLeak = graph.summary.substitution['library(titan)']
  const leakText = (libLeak?.Text ?? 0) + (libLeak?.View ?? 0)
  return (
    <div
      style={{
        padding: 28,
        background: C['background-base'],
        minHeight: '100vh',
        fontFamily: 'Inter, sans-serif',
      }}
    >
      <h1 style={{ color: C['text-primary'], fontSize: 26, fontWeight: 800, margin: 0 }}>
        Component Architecture
      </h1>
      <p style={{ color: C['text-secondary'], fontSize: 14, margin: '6px 0 16px', maxWidth: 760 }}>
        Deterministic dependency + health map from the codewatch symbol graph and the consuming
        apps. Node label shows <span style={{ fontFamily: 'monospace' }}>lib·app</span> usage.
        Regenerate:{' '}
        <span style={{ fontFamily: 'monospace', color: C['text-primary'] }}>
          node scripts/arch-graph.mjs --reindex
        </span>
        .
      </p>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 8 }}>
        <Chip color={C['text-secondary']}>{graph.components.length} components</Chip>
        <Chip color={C['status-error-vivid']}>{dead} dead everywhere</Chip>
        <Chip color={C['status-warning']}>{leakText} raw Text/View leaks in-library</Chip>
        {graph.summary.consumers.map((c) => (
          <Chip key={c.name} color={c.present ? C['status-success'] : C['text-tertiary']}>
            {c.name}
            {c.present ? '' : ' (absent)'}
          </Chip>
        ))}
      </div>

      <Section
        title="Dependency diagram"
        subtitle="Columns by composition depth (leaves = atoms). Hover a node to trace what it composes / is composed by. Border color = verdict."
      >
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 10 }}>
          {Object.entries(VERDICT).map(([k, v]) => (
            <Chip key={k} color={v.color}>
              {v.label}
            </Chip>
          ))}
        </div>
        <Diagram />
      </Section>

      <Section
        title="Dead & unshipped"
        subtitle="Zero production dependents in the library AND zero imports across all consuming apps — only their own story references them."
      >
        <DeadTable />
      </Section>

      <Section
        title="Primitive-substitution leaks"
        subtitle="Files importing a raw RN primitive that a titan atom already covers (Text→Typography, View→Surface/Stack, Pressable→Button…). The library bypassing its own primitives is the root cause of drift."
      >
        <SubstitutionTable />
      </Section>

      <Section
        title="Extraction candidates"
        subtitle="Highest inline-primitive density — repeated raw <View>/<Text>/style blocks and hardcoded hex that could be promoted into reusable primitives. rawHex flags token violations."
      >
        <ExtractionTable />
      </Section>
    </div>
  )
}

const meta: Meta = {
  title: 'Docs/Architecture',
  parameters: { layout: 'fullscreen' },
}
export default meta
type Story = StoryObj

export const Overview: Story = { render: () => <ArchitecturePage /> }
